### ISSUE TITLE
Unable to activate RailDriver in 1.4.8

### ISSUE THREAD

**Issue by TrainzLuvr** [perpetualKid/ORTS-MG#117]
Hi,

I've installed and can run 1.4.8 using the keyboard/mouse just fine. But with my RailDriver I am having no luck at all.

After calibrating RD though Options/RailDriver tab, I launch a scenario and the RD just shows ---

When everything loads, I press RailDriver Run/Stop (button 14) which normally activates RD, but in this case nothing happens.

FWIW, RD works as expected in official OR 1.5.1 with ModernCalibration.rdm, but I'd like to use it here. :)

Any ideas?

Thanks!

**Comment by perpetualKid** [comment]
When in game, Raildriver needs to be activated from keyboard, default using the "`" key (left from 1 key in the number row on english keyboard).
This is intentional to allow the player to set/reset the Raildriver handles when starting the game and prevent arbitrary input. 

The key is also configurable in Menu Options as "External Input Device", but maybe an idea also to make it configurable whether Raildriver is activated by default...

**Comment by perpetualKid** [comment]
btw this is also documented in our wiki https://github.com/perpetualKid/ORTS-MG/wiki/RailDriver-Support

**Comment by TrainzLuvr** [comment]
I have to admit, I went to the Wiki page and glanced over it without noticing there is an index of pages in the right column, where RailDriver Support was.

Thanks for the quick response.
